In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])    

In [2]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
X = np.zeros((3,4), dtype = int)
print(X)
print('dtype: ', X.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
dtype:  int32


In [8]:
X = np.full((3,4),10)
print(X)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [13]:
X = np.eye(5, dtype=int)
print(X)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [14]:
X = np.diag([1,3,5,7,9])
print(X)

[[1 0 0 0 0]
 [0 3 0 0 0]
 [0 0 5 0 0]
 [0 0 0 7 0]
 [0 0 0 0 9]]


In [15]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [17]:
x = np.reshape(x, (4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [22]:
Y = np.arange(20).reshape(2,10)
print(Y)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [26]:
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)
print(X)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


In [28]:
X = np.random.random((4,5))
print(X)

[[0.44840414 0.93640299 0.93570188 0.35489177 0.64671882]
 [0.64710484 0.6826423  0.07435126 0.6189031  0.0374363 ]
 [0.94420168 0.97121143 0.20200549 0.65935831 0.68121449]
 [0.05435947 0.47310417 0.2000895  0.56402025 0.42296188]]


In [29]:
X = np.random.randint(1, 12, (4,3))
print(X)

[[11  4  7]
 [ 4  6  3]
 [ 2  2 11]
 [ 4  8  3]]


In [31]:
x = np.random.normal(0, 1, size=(5,5))
print(x)

[[ 0.44834509  0.08942263  0.57844104  0.2392041  -0.5063277 ]
 [-1.78371202  1.08189176  0.27965064  0.9061837  -0.42527391]
 [ 0.28173506 -1.41228239 -1.91929599 -2.55607182 -0.62950146]
 [ 0.71136257 -1.2082577  -2.33638245  2.08874463 -0.62477895]
 [-0.67621587  0.64361782 -0.2992491  -1.13415208 -1.09239124]]


In [6]:
import numpy as np
x = np.array([1, 2, 3, 4, 5])
print(x)


[1 2 3 4 5]


In [8]:
print('1st element', x[0])
print('3rd element', x[2])

1st element 1
3rd element 3


In [9]:
x[3]=20
print(x)

[ 1  2  3 20  5]


In [11]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
print('This is 0,0 element: ', x[0,0])
print('This is 2,3 element: ', x[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
This is 0,0 element:  1
This is 2,3 element:  9


In [9]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
x = np.array([6,7,8,9,0])
print(x)

x = np.delete(x,[0,4])
print(x)

[6 7 8 9 0]
[7 8 9]


In [12]:
x = np.arange(1,10).reshape(3,3)
print(x)

y = np.delete(x, 0, axis=0)
print('\n',y)

z = np.delete(x, [0,2], axis=1)
print('\n',z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


In [15]:
x = np.array([1,2,3,4,5])
print(x)
x = np.append(x,[6,7,8])
print(x)
x = np.append(x,[6,1,2,3,4])
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8 6 1 2 3 4]


In [23]:
y = np.arange(1,10).reshape(3,3)
print(y)
z = np.append(y, [[10,11,12]], axis=0)
print(z)
a = np.append(y, [[10],[11],[12]], axis=1)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [26]:
x = np.array([1,2,3,6,7])
print (x)
x = np.insert(x,3,[4,5])
print(x)

[1 2 3 6 7]
[1 2 3 4 5 6 7]


In [29]:
y = np.array([[1,2,3],[7,8,9]])
print(y)
z = np.insert(y,1,[4,5,6], axis=0)
print(z)

[[1 2 3]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
x = np.arange(1,21).reshape(4,5)
print(x)
z = x[1:4, 2:5] #row 2,3,4 and columns 3,4,5
print('\n',z) 
a = x[:,2] #column 3
print('\n',a)
b = x[:3,:2] #rows 1,2,3 and colums 1,2
print('\n',b)
c = x[:, 2:3]
print('\n',c) #column 3 in a rank 2 array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]

 [ 3  8 13 18]

 [[ 1  2]
 [ 6  7]
 [11 12]]

 [[ 3]
 [ 8]
 [13]
 [18]]


In [6]:
import numpy as np
x = np.arange(25).reshape(5,5)
print(x)
print(x[x>10])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [7]:
 print(x[(x>10) & (x<17)])

[11 12 13 14 15 16]


In [9]:
x = np.random.randint(1,11, size=(10,))
print(x)

[9 6 7 4 1 6 8 5 2 6]


In [11]:
print(np.sort(x))
print(x)

[1 2 4 5 6 6 6 7 8 9]
[9 6 7 4 1 6 8 5 2 6]
